CREATE TABLE IF NOT EXISTS ai_rate_limits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    request_count INT NOT NULL DEFAULT 0,
    window_start TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS ai_user_preferences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    meal_name VARCHAR(255) NOT NULL,
    tags TEXT,
    meal_type VARCHAR(255),
    created_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_ai_user_preferences_user_id ON ai_user_preferences(user_id);
CREATE INDEX idx_ai_user_preferences_created_at ON ai_user_preferences(created_at);
