ALTER TABLE users ADD COLUMN IF NOT EXISTS premium_plan VARCHAR(20);
ALTER TABLE users ADD COLUMN IF NOT EXISTS premium_cancel_at_period_end BOOLEAN DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS premium_canceled_at TIMESTAMP;
