package com.fitness.entity;

import java.time.LocalDateTime;
import java.util.List;

import io.quarkus.hibernate.orm.panache.PanacheEntity;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * Stores in-app notifications generated by the AI or the system.
 */
@Entity
@Table(name = "notifications")
public class Notification extends PanacheEntity {

    @ManyToOne
    public User user;

    @Column(nullable = false)
    public String title;

    @Column(columnDefinition = "TEXT", nullable = false)
    public String message;

    @Column(name = "is_read")
    public boolean isRead = false;

    @Column(name = "created_at")
    public LocalDateTime createdAt;

    public String type; // e.g., "AI_COACH", "SYSTEM", "ACHIEVEMENT"

    public Notification() {
        this.createdAt = LocalDateTime.now();
    }

    public static List<Notification> findUnreadByUser(Long userId) {
        return find("user.id = ?1 and isRead = false order by createdAt desc", userId).list();
    }
}
