part of 'nutrition_guide_page.dart';

const _goals = <_Goal>[
  _Goal(
    key: 'cut',
    label: 'Kilo Ver',
    emoji: '🔥',
    color: Color(0xFFFF453A),
    subtitle: 'Yağ yakarken kas koru',
    calorieRule: '−300 – 500 kcal/gün açığı',
    macros: [
      _Macro(
        name: 'Protein',
        amount: '2.0–2.4 g/kg',
        ratio: 0.35,
        color: Color(0xFFFF453A),
      ),
      _Macro(
        name: 'Karbonhidrat',
        amount: '3–4 g/kg',
        ratio: 0.40,
        color: Color(0xFFFF9F0A),
      ),
      _Macro(
        name: 'Yağ',
        amount: '0.8–1.0 g/kg',
        ratio: 0.25,
        color: Color(0xFF30D158),
      ),
    ],
    meals: [
      _MealIdea(
        name: 'Tavuklu Salata',
        detail: '~400 kcal · 40g pro',
        icon: Icons.lunch_dining_rounded,
        accent: Color(0xFFFF453A),
      ),
      _MealIdea(
        name: 'Yulaf + Yumurta',
        detail: '~350 kcal · 25g pro',
        icon: Icons.free_breakfast_rounded,
        accent: Color(0xFFFF9F0A),
      ),
      _MealIdea(
        name: 'Ton Balıklı Tam Tahıl',
        detail: '~300 kcal · 30g pro',
        icon: Icons.wrap_text_rounded,
        accent: Color(0xFF30D158),
      ),
      _MealIdea(
        name: 'Izgara Balık + Sebze',
        detail: '~360 kcal · 35g pro',
        icon: Icons.set_meal_rounded,
        accent: Color(0xFF0A84FF),
      ),
      _MealIdea(
        name: 'Süzme Yoğurt + Ceviz',
        detail: '~200 kcal · 18g pro',
        icon: Icons.icecream_rounded,
        accent: Color(0xFFBF5AF2),
      ),
    ],
    rules: [
      'Her öğünde protein önce yenilsin',
      'Kalori saymak yerine besin yoğunluğuna odaklan',
      'Günde en az 2.5L su iç — açlık hissini azaltır',
      'Gece geç saatte karbonhidrat alımını kısıt',
      'Haftalık 0.5–1 kg kayıp ideal hız',
    ],
    avoid: [
      'Şeker ve işlenmiş atıştırmalıklar',
      'Alkol — kalori yoğun olabilir ve toparlanmayı zorlaştırabilir',
      'Beyaz ekmek ve rafine karbonhidrat',
      'Kızartmalar ve fast food',
    ],
    dailyPlan: [
      _DayMeal(
        time: '07:30',
        label: 'Kahvaltı',
        food: 'Yulaf ezmesi + 2 haşlanmış yumurta + yarım muz',
        macros: '~380 kcal · 28g pro',
        icon: Icons.free_breakfast_rounded,
      ),
      _DayMeal(
        time: '10:30',
        label: 'Ara Öğün',
        food: 'Süzme yoğurt + bir avuç ceviz',
        macros: '~200 kcal · 18g pro',
        icon: Icons.bakery_dining_rounded,
      ),
      _DayMeal(
        time: '13:00',
        label: 'Öğle',
        food: 'Fırın tavuk göğsü + mevsim salatası + zeytinyağı',
        macros: '~450 kcal · 42g pro',
        icon: Icons.lunch_dining_rounded,
      ),
      _DayMeal(
        time: '16:30',
        label: 'Antrenman Öncesi',
        food: 'Muz veya 1 dilim tam tahıl ekmek + az peynir',
        macros: '~150 kcal · 7g pro',
        icon: Icons.fitness_center_rounded,
      ),
      _DayMeal(
        time: '20:00',
        label: 'Akşam',
        food: 'Izgara balık (levrek/çipura) + buharda sebze + bulgur',
        macros: '~480 kcal · 38g pro',
        icon: Icons.dinner_dining_rounded,
      ),
    ],
    topFoods: [
      _TopFood(
        name: 'Tavuk Göğsü',
        highlight: 'En yüksek protein/kcal oranı',
        color: Color(0xFFFF453A),
      ),
      _TopFood(
        name: 'Yumurta',
        highlight: 'Tam protein + doyurucu',
        color: Color(0xFFFF9F0A),
      ),
      _TopFood(
        name: 'Süzme Yoğurt',
        highlight: 'Yüksek protein + probiyotik',
        color: Color(0xFF30D158),
      ),
      _TopFood(
        name: 'Levrek / Çipura',
        highlight: 'Omega-3 + yüksek pro',
        color: Color(0xFF0A84FF),
      ),
      _TopFood(
        name: 'Brokoli / Ispanak',
        highlight: 'Yüksek lif, düşük kcal',
        color: Color(0xFF34C759),
      ),
      _TopFood(
        name: 'Ton Balığı',
        highlight: 'Uygun fiyat, yüksek pro',
        color: Color(0xFFBF5AF2),
      ),
    ],
    timing: _Timing(
      preMeal: 'Antrenman 60–90 dk Önce',
      postMeal: 'Antrenman 30 dk Sonra',
      preDetail:
          'Orta GI karbonhidrat + az protein. Örnek: yulaf ezmesi + lor peyniri veya muz + yoğurt.',
      postDetail:
          'Hızlı sindirilen protein + basit karb. Örnek: whey shake + muz veya yağsız yoğurt + meyve.',
    ),
    supplements: [
      'Whey Protein',
      'Kreatin 5g',
      'Multivitamin',
      'Omega-3',
      'D3 Vitamini',
    ],
  ),
  _Goal(
    key: 'gain',
    label: 'Kilo Al',
    emoji: '📈',
    color: Color(0xFF30D158),
    subtitle: 'Sağlıklı ve kademeli artış',
    calorieRule: '+300 – 500 kcal/gün fazlası',
    macros: [
      _Macro(
        name: 'Protein',
        amount: '1.6–2.0 g/kg',
        ratio: 0.28,
        color: Color(0xFF30D158),
      ),
      _Macro(
        name: 'Karbonhidrat',
        amount: '5–6 g/kg',
        ratio: 0.50,
        color: Color(0xFFFF9F0A),
      ),
      _Macro(
        name: 'Yağ',
        amount: '1.0–1.5 g/kg',
        ratio: 0.22,
        color: Color(0xFF0A84FF),
      ),
    ],
    meals: [
      _MealIdea(
        name: 'Yulaf + Muz Smoothie',
        detail: '~550 kcal · 25g pro',
        icon: Icons.blender_rounded,
        accent: Color(0xFF30D158),
      ),
      _MealIdea(
        name: 'Pirinç + Tavuk + Zeytinyağı',
        detail: '~650 kcal · 45g pro',
        icon: Icons.rice_bowl_rounded,
        accent: Color(0xFFFF9F0A),
      ),
      _MealIdea(
        name: 'Fındık Ezmeli Tam Tahıl',
        detail: '~420 kcal · 15g pro',
        icon: Icons.bakery_dining_rounded,
        accent: Color(0xFFFF453A),
      ),
      _MealIdea(
        name: 'Yumurta + Avokado',
        detail: '~480 kcal · 20g pro',
        icon: Icons.egg_alt_rounded,
        accent: Color(0xFF0A84FF),
      ),
      _MealIdea(
        name: 'Makarna + Kıyma',
        detail: '~700 kcal · 40g pro',
        icon: Icons.dinner_dining_rounded,
        accent: Color(0xFFBF5AF2),
      ),
    ],
    rules: [
      '4–5 öğünle günlük kalorileri yay',
      'Antrenman öncesi karbonhidrat yükle',
      'Antrenman sonrası 30dk içinde protein al',
      'Haftalık 0.3–0.5 kg artış ideal',
      'Uyku en az 8 saat — büyüme hormonuna kritik',
    ],
    avoid: [
      'Uzun süreli açlık ve atlanmış öğünler',
      'Sadece yağlı/şekerli besinlerle kalori artırma',
      'Aşırı kafein — iştah bastırır',
      'Kilo alma adına çöp kalori',
    ],
    dailyPlan: [
      _DayMeal(
        time: '07:00',
        label: 'Kahvaltı',
        food: 'Yulaf + yumurta + fındık ezmesi + muz',
        macros: '~600 kcal · 30g pro',
        icon: Icons.free_breakfast_rounded,
      ),
      _DayMeal(
        time: '10:00',
        label: 'Ara Öğün',
        food: 'Tam yağlı yoğurt + meyve + ceviz',
        macros: '~320 kcal · 16g pro',
        icon: Icons.bakery_dining_rounded,
      ),
      _DayMeal(
        time: '13:00',
        label: 'Öğle',
        food: 'Pirinç pilav + tavuk + zeytinyağı',
        macros: '~700 kcal · 48g pro',
        icon: Icons.rice_bowl_rounded,
      ),
      _DayMeal(
        time: '16:00',
        label: 'Antrenman Öncesi',
        food: 'Muz + 1 dilim tam tahıl ekmek',
        macros: '~200 kcal · 5g pro',
        icon: Icons.fitness_center_rounded,
      ),
      _DayMeal(
        time: '19:30',
        label: 'Akşam',
        food: 'Makarna + kıyma sosu + kaşar rendesi',
        macros: '~750 kcal · 42g pro',
        icon: Icons.dinner_dining_rounded,
      ),
    ],
    topFoods: [
      _TopFood(
        name: 'Yulaf',
        highlight: 'Kalori + lif + uzun enerji',
        color: Color(0xFF30D158),
      ),
      _TopFood(
        name: 'Pirinç / Bulgur',
        highlight: 'Hızlı sindirim, yüksek karb',
        color: Color(0xFFFF9F0A),
      ),
      _TopFood(
        name: 'Fındık Ezmesi',
        highlight: 'Sağlıklı yağ + kalori',
        color: Color(0xFFFF453A),
      ),
      _TopFood(
        name: 'Muz',
        highlight: 'Hızlı enerji + potasyum',
        color: Color(0xFF0A84FF),
      ),
      _TopFood(
        name: 'Tavuk Göğsü',
        highlight: 'Yüksek protein + düşük yağ',
        color: Color(0xFF30D158),
      ),
      _TopFood(
        name: 'Zeytinyağı',
        highlight: 'Kalori yoğun + sağlıklı',
        color: Color(0xFFBF5AF2),
      ),
    ],
    timing: _Timing(
      preMeal: 'Antrenman 60 dk Önce',
      postMeal: 'Antrenman 30 dk Sonra',
      preDetail:
          'Yüksek karbonhidrat + orta protein. Örnek: pirinç + tavuk veya yulaf + yumurta.',
      postDetail:
          'Protein + hızlı karb kombinasyonu. Örnek: whey + muz + pirinç keki veya yoğurt + granola.',
    ),
    supplements: [
      'Whey Protein',
      'Kreatin 5g',
      'Protein tozu (gerekiyorsa)',
      'Magnezyum/çinko (eksiklikte)',
      'B12 Vitamini',
    ],
  ),
  _Goal(
    key: 'bulk',
    label: 'Hacim',
    emoji: '💪',
    color: Color(0xFFBF5AF2),
    subtitle: 'Maksimum kas kütlesi',
    calorieRule: '+500 – 1000 kcal/gün fazlası',
    macros: [
      _Macro(
        name: 'Protein',
        amount: '1.8–2.4 g/kg',
        ratio: 0.30,
        color: Color(0xFFBF5AF2),
      ),
      _Macro(
        name: 'Karbonhidrat',
        amount: '6–8 g/kg',
        ratio: 0.50,
        color: Color(0xFFFF9F0A),
      ),
      _Macro(
        name: 'Yağ',
        amount: '1.0–1.5 g/kg',
        ratio: 0.20,
        color: Color(0xFF30D158),
      ),
    ],
    meals: [
      _MealIdea(
        name: 'Yoğurtlu Muz Shake',
        detail: '~550 kcal · 30g pro',
        icon: Icons.local_drink_rounded,
        accent: Color(0xFFBF5AF2),
      ),
      _MealIdea(
        name: 'Kırmızı Et + Patates',
        detail: '~750 kcal · 50g pro',
        icon: Icons.outdoor_grill_rounded,
        accent: Color(0xFFFF453A),
      ),
      _MealIdea(
        name: 'Pirinç Pilav + Mercimek',
        detail: '~600 kcal · 30g pro',
        icon: Icons.rice_bowl_rounded,
        accent: Color(0xFFFF9F0A),
      ),
      _MealIdea(
        name: 'Tam Yağlı Süt + Yulaf',
        detail: '~500 kcal · 22g pro',
        icon: Icons.local_cafe_rounded,
        accent: Color(0xFF0A84FF),
      ),
      _MealIdea(
        name: 'Hindi Saç + Ekmek',
        detail: '~680 kcal · 55g pro',
        icon: Icons.lunch_dining_rounded,
        accent: Color(0xFF30D158),
      ),
    ],
    rules: [
      'Her 2–3 saatte öğün ye — anabolik pencere',
      'Yatmadan önce kazein veya yoğurt al',
      'Ağır bileşik hareketlere odaklan',
      'Creatine monohydrate günde 5g ekle',
      'Karın yağı %15 altındayken bulk daha etkili',
    ],
    avoid: [
      'Cardio ağırlıklı program — kalori yakıyor',
      'Yetersiz karbonhidrat — enerji düşer',
      'Öğün atlamak — katabolizma riski',
      'Uyku eksikliği — hormon profili bozulur',
    ],
    dailyPlan: [
      _DayMeal(
        time: '07:00',
        label: 'Kahvaltı',
        food: '4 yumurta + yulaf + süt + muz',
        macros: '~750 kcal · 45g pro',
        icon: Icons.free_breakfast_rounded,
      ),
      _DayMeal(
        time: '10:00',
        label: 'Ara Öğün',
        food: 'Süt + yulaf + muz + fındık karışımı',
        macros: '~550 kcal · 28g pro',
        icon: Icons.local_drink_rounded,
      ),
      _DayMeal(
        time: '13:00',
        label: 'Öğle',
        food: 'Kırmızı et + pirinç pilav + salata',
        macros: '~850 kcal · 55g pro',
        icon: Icons.outdoor_grill_rounded,
      ),
      _DayMeal(
        time: '16:00',
        label: 'Antrenman',
        food: 'Whey + dextrose veya muz + pirinç keki',
        macros: '~350 kcal · 35g pro',
        icon: Icons.fitness_center_rounded,
      ),
      _DayMeal(
        time: '19:30',
        label: 'Akşam',
        food: 'Hindi + patates + zeytinyağı',
        macros: '~800 kcal · 58g pro',
        icon: Icons.dinner_dining_rounded,
      ),
      _DayMeal(
        time: '22:00',
        label: 'Gece',
        food: 'Süzme yoğurt veya lor peyniri + ceviz',
        macros: '~220 kcal · 22g pro',
        icon: Icons.nightlight_rounded,
      ),
    ],
    topFoods: [
      _TopFood(
        name: 'Kırmızı Et',
        highlight: 'Kreatin + demir + pro',
        color: Color(0xFFBF5AF2),
      ),
      _TopFood(
        name: 'Yulaf',
        highlight: 'Kompleks karb + kalori',
        color: Color(0xFFFF9F0A),
      ),
      _TopFood(
        name: 'Tam Yağlı Süt',
        highlight: 'Kalori + kazein + pro',
        color: Color(0xFF0A84FF),
      ),
      _TopFood(
        name: 'Pirinç',
        highlight: 'Hızlı glikojen doldurma',
        color: Color(0xFF30D158),
      ),
      _TopFood(
        name: 'Yumurta',
        highlight: 'Tam aminoasit profili',
        color: Color(0xFFFF453A),
      ),
      _TopFood(
        name: 'Avokado',
        highlight: 'Sağlıklı yağ + kalori',
        color: Color(0xFF34C759),
      ),
    ],
    timing: _Timing(
      preMeal: 'Antrenman 45–60 dk Önce',
      postMeal: 'Antrenman 20 dk Sonra',
      preDetail:
          'Yüksek karb + protein. Örnek: pirinç + tavuk + az yağ. Sindirimi kolay tutun.',
      postDetail:
          'Antrenman sonrası protein + karbonhidrat toparlanmayı destekleyebilir. Örnek: whey + pirinç + muz kombinasyonu.',
    ),
    supplements: [
      'Whey Protein',
      'Kreatin 5g',
      'Protein tozu (gerekiyorsa)',
      'BCAA',
      'Glutamin',
      'Magnezyum/çinko (eksiklikte)',
    ],
  ),
  _Goal(
    key: 'strength',
    label: 'Güç',
    emoji: '⚡',
    color: Color(0xFFFF9F0A),
    subtitle: 'Performans & kuvvet odaklı',
    calorieRule: 'Dengeli / +100–200 kcal',
    macros: [
      _Macro(
        name: 'Protein',
        amount: '1.8–2.2 g/kg',
        ratio: 0.30,
        color: Color(0xFFFF9F0A),
      ),
      _Macro(
        name: 'Karbonhidrat',
        amount: '4–6 g/kg',
        ratio: 0.45,
        color: Color(0xFF30D158),
      ),
      _Macro(
        name: 'Yağ',
        amount: '1.0–1.2 g/kg',
        ratio: 0.25,
        color: Color(0xFF0A84FF),
      ),
    ],
    meals: [
      _MealIdea(
        name: 'Antrenman Öncesi Yulaf',
        detail: '~400 kcal · 15g pro',
        icon: Icons.bolt_rounded,
        accent: Color(0xFFFF9F0A),
      ),
      _MealIdea(
        name: 'Whey + Muz (Sonrası)',
        detail: '~300 kcal · 30g pro',
        icon: Icons.fitness_center_rounded,
        accent: Color(0xFFBF5AF2),
      ),
      _MealIdea(
        name: 'Tavuk + Tatlı Patates',
        detail: '~580 kcal · 45g pro',
        icon: Icons.rice_bowl_rounded,
        accent: Color(0xFF30D158),
      ),
      _MealIdea(
        name: 'Yumurta Beyazı + Tam Tahıl',
        detail: '~350 kcal · 28g pro',
        icon: Icons.egg_rounded,
        accent: Color(0xFFFF453A),
      ),
      _MealIdea(
        name: 'Kırmızı Et + Bulgur',
        detail: '~620 kcal · 50g pro',
        icon: Icons.outdoor_grill_rounded,
        accent: Color(0xFF0A84FF),
      ),
    ],
    rules: [
      'Antrenman 90dk öncesi karb + protein al',
      'Kafein (200mg) 45dk öncesi performansı artırır',
      'Creatine — kuvvet için kanıtlanmış tek takviye',
      'Yeterince kaloride olmadan kuvvet gelişmez',
      'Deload haftasında kaloriyi %10 düşür',
    ],
    avoid: [
      'Antrenman öncesi yüksek yağlı öğün',
      'Düşük karbonhidrat diyeti — güç düşer',
      'Takviye bağımlılığı — önce beslenme',
      'Alkol — toparlanmayı engeller',
    ],
    dailyPlan: [
      _DayMeal(
        time: '07:30',
        label: 'Kahvaltı',
        food: 'Yulaf + 3 yumurta + ceviz',
        macros: '~520 kcal · 35g pro',
        icon: Icons.free_breakfast_rounded,
      ),
      _DayMeal(
        time: '11:00',
        label: 'Ara Öğün',
        food: 'Tam buğday ekmek + hindi + avokado',
        macros: '~380 kcal · 28g pro',
        icon: Icons.bakery_dining_rounded,
      ),
      _DayMeal(
        time: '14:00',
        label: 'Öğle',
        food: 'Kırmızı et + bulgur pilavı + ıspanak',
        macros: '~650 kcal · 52g pro',
        icon: Icons.outdoor_grill_rounded,
      ),
      _DayMeal(
        time: '17:00',
        label: 'Antrenman Öncesi',
        food: 'Tatlı patates + tavuk + kafein',
        macros: '~420 kcal · 35g pro',
        icon: Icons.fitness_center_rounded,
      ),
      _DayMeal(
        time: '20:30',
        label: 'Akşam',
        food: 'Somon + brokoli + pirinç',
        macros: '~580 kcal · 45g pro',
        icon: Icons.dinner_dining_rounded,
      ),
    ],
    topFoods: [
      _TopFood(
        name: 'Sığır Eti',
        highlight: 'Kreatin + demir + çinko',
        color: Color(0xFFFF9F0A),
      ),
      _TopFood(
        name: 'Bulgur',
        highlight: 'Lif + demir + kompleks karb',
        color: Color(0xFF30D158),
      ),
      _TopFood(
        name: 'Tatlı Patates',
        highlight: 'Sürekli enerji kaynağı',
        color: Color(0xFFFF453A),
      ),
      _TopFood(
        name: 'Somon',
        highlight: 'Omega-3 + toparlanma',
        color: Color(0xFF0A84FF),
      ),
      _TopFood(
        name: 'Yumurta',
        highlight: 'Tam aminoasit profili',
        color: Color(0xFFBF5AF2),
      ),
      _TopFood(
        name: 'Kahve / Kafein',
        highlight: 'Performans artırıcı',
        color: Color(0xFF8D6E63),
      ),
    ],
    timing: _Timing(
      preMeal: 'Antrenman 60–90 dk Önce',
      postMeal: 'Antrenman 30 dk Sonra',
      preDetail:
          'Kompleks karb + orta protein + kafein (opsiyonel). Örnek: bulgur + kıyma köfte veya yulaf + yumurta.',
      postDetail:
          'Kas onarımı için protein + karbonhidrat. Whey + meyve veya yoğurt + muz pratik olabilir; kreatin zamanlamasında günlük düzen daha önemlidir.',
    ),
    supplements: [
      'Kreatin 5g',
      'Kafein 200mg',
      'Whey Protein',
      'Omega-3',
      'Magnezyum',
    ],
  ),
  _Goal(
    key: 'maintain',
    label: 'Form Koru',
    emoji: '⚖️',
    color: Color(0xFF0A84FF),
    subtitle: 'Mevcut formu ve kiloyu koru',
    calorieRule: 'TDEE = sıfır açık/fazla',
    macros: [
      _Macro(
        name: 'Protein',
        amount: '1.4–1.8 g/kg',
        ratio: 0.25,
        color: Color(0xFF0A84FF),
      ),
      _Macro(
        name: 'Karbonhidrat',
        amount: '4–5 g/kg',
        ratio: 0.50,
        color: Color(0xFFFF9F0A),
      ),
      _Macro(
        name: 'Yağ',
        amount: '1.0 g/kg',
        ratio: 0.25,
        color: Color(0xFF30D158),
      ),
    ],
    meals: [
      _MealIdea(
        name: 'Omlet + Sebze',
        detail: '~350 kcal · 22g pro',
        icon: Icons.egg_alt_rounded,
        accent: Color(0xFF0A84FF),
      ),
      _MealIdea(
        name: 'Izgara Balık + Salata',
        detail: '~420 kcal · 35g pro',
        icon: Icons.set_meal_rounded,
        accent: Color(0xFF30D158),
      ),
      _MealIdea(
        name: 'Bulgur Pilavı + Yoğurt',
        detail: '~480 kcal · 20g pro',
        icon: Icons.rice_bowl_rounded,
        accent: Color(0xFFFF9F0A),
      ),
      _MealIdea(
        name: 'Meyve + Ceviz',
        detail: '~250 kcal · 5g pro',
        icon: Icons.eco_rounded,
        accent: Color(0xFF30D158),
      ),
      _MealIdea(
        name: 'Mercimek Çorbası',
        detail: '~300 kcal · 18g pro',
        icon: Icons.soup_kitchen_rounded,
        accent: Color(0xFFFF453A),
      ),
    ],
    rules: [
      'Kilonu haftada bir takip et — trend izle',
      'Dengeli tabak: ½ sebze, ¼ protein, ¼ karb',
      'Egzersiz rutinini koru — hafta 3–4 gün',
      'Stres ve uyku kalitesi formda kritik',
      'Hafta 1 gün serbest öğün motivasyonu artırır',
    ],
    avoid: [
      'Tutarsız beslenme düzeni — yoyo yapar',
      'Aşırı kısıtlama veya aşırı yeme',
      'Hareketsiz uzun dönemler',
      'Kontrolsüz sosyal yemek periyotları',
    ],
    dailyPlan: [
      _DayMeal(
        time: '08:00',
        label: 'Kahvaltı',
        food: '2 yumurta + tam tahıl ekmek + domates',
        macros: '~380 kcal · 22g pro',
        icon: Icons.free_breakfast_rounded,
      ),
      _DayMeal(
        time: '11:00',
        label: 'Ara Öğün',
        food: 'Meyve + bir avuç fındık',
        macros: '~200 kcal · 5g pro',
        icon: Icons.eco_rounded,
      ),
      _DayMeal(
        time: '13:30',
        label: 'Öğle',
        food: 'Bulgur + ızgara tavuk + cacık',
        macros: '~520 kcal · 38g pro',
        icon: Icons.rice_bowl_rounded,
      ),
      _DayMeal(
        time: '16:30',
        label: 'Ara Öğün',
        food: 'Yoğurt veya kefir',
        macros: '~150 kcal · 10g pro',
        icon: Icons.icecream_rounded,
      ),
      _DayMeal(
        time: '19:30',
        label: 'Akşam',
        food: 'Izgara balık + mercimek çorbası + salata',
        macros: '~500 kcal · 42g pro',
        icon: Icons.set_meal_rounded,
      ),
    ],
    topFoods: [
      _TopFood(
        name: 'Bulgur',
        highlight: 'Lif + demir + dengeli karb',
        color: Color(0xFF0A84FF),
      ),
      _TopFood(
        name: 'Mercimek',
        highlight: 'Protein + lif + demir',
        color: Color(0xFFFF9F0A),
      ),
      _TopFood(
        name: 'Yoğurt',
        highlight: 'Probiyotik + kalsiyum',
        color: Color(0xFF30D158),
      ),
      _TopFood(
        name: 'Balık',
        highlight: 'Omega-3 + yüksek pro',
        color: Color(0xFF0A84FF),
      ),
      _TopFood(
        name: 'Sebze Çeşitleri',
        highlight: 'Mikro besin deposu',
        color: Color(0xFF34C759),
      ),
      _TopFood(
        name: 'Zeytinyağı',
        highlight: 'Anti-enflamatuar yağ',
        color: Color(0xFFFF453A),
      ),
    ],
    timing: _Timing(
      preMeal: 'Egzersiz 60 dk Önce',
      postMeal: 'Egzersiz 45 dk Sonra',
      preDetail:
          'Hafif ve sindirimi kolay öğün. Yoğurt veya 1 dilim tam tahıl ekmek + beyaz peynir yeterli.',
      postDetail:
          'Normal öğün yeterli. Tavuk, yumurta veya yoğurt ağırlıklı tercih form korumayı destekler.',
    ),
    supplements: [
      'Multivitamin',
      'D3 + K2',
      'Omega-3',
      'Magnezyum',
      'C Vitamini',
    ],
  ),
];

// ─── Sayfa ────────────────────────────────────────────────────────────────────
