-- Yeni Başlayanlar İçin Detaylandırılmış Egzersiz Veri Seti
-- Kas grupları: CHEST, BACK, LEGS, SHOULDERS, BICEPS, TRICEPS, CORE, GLUTES

INSERT INTO exercises (id, muscle_group, name, description, instructions, tips) VALUES
-- CHEST
(1, 'CHEST', 'Flat Bench Press', 'Göğüs, ön omuz ve triceps çalıştıran temel bir güç hareketidir.', 
'1. Banka sırt üstü uzan ve ayaklarını yere sağlamca bas.\n2. Barı omuz genişliğinden biraz daha geniş bir açıyla kavra.\n3. Barı raktan çıkar ve göğüs hizasına getir.\n4. Nefes alarak barı yavaşça göğüs kafesine (meme ucu hizası) doğru indir.\n5. Bar göğsüne hafifçe değdiğinde, nefes vererek barı başlangıç pozisyonuna doğru güçlüce it.', 
'Bileklerini bükme, barı omuz genişliğinden biraz daha geniş tut.'),

(2, 'CHEST', 'Incline Dumbbell Press', 'Üst göğüs liflerini hedefleyen etkili bir pres hareketidir.', 
'1. Sehpaya 30-45 derece eğim ver ve üzerine uzan.\n2. İki eline birer dumbbell al ve omuz hizasında tut.\n3. Ayaklarını yere basarak denge sağla.\n4. Nefes vererek ağırlıkları tavan yönünde birbirine yaklaştırarak it.\n5. Tepe noktada göğüs kaslarını sık ve nefes alarak ağırlıkları yavaşça omuz hizasına geri indir.', 
'Dirseğin açısını 45 derecede tutarak omuz sakatlıklarını önle.'),

(3, 'CHEST', 'Decline Bench Press', 'Alt göğüs bölgesini şekillendirmek için kullanılır.', 
'1. Aşağı eğimli sehpaya uzan ve ayaklarını desteklere kilitle.\n2. Barı omuz genişliğinden biraz daha geniş kavra.\n3. Barı kontrollü şekilde alt göğüs çizgisine doğru indir.\n4. Göğüs kaslarını hissederek ağırlığı yukarı doğru it.\n5. Hareketi yaparken belini sehpadan ayırmamaya çalış.', 
'Kan akışının başa toplanmaması için set aralarında kalkıp biraz yürü.'),

(4, 'CHEST', 'Cable Fly', 'Göğüs kaslarını izole eden ve gerilimi sürekli tutan bir harekettir.', 
'1. Kablo makinesinin ortasında dur ve tutacakları kavra.\n2. Bir adım öne çıkarak denge al, dizlerini hafifçe bük.\n3. Kollarını yanlara doğru, dirseklerini kırmadan aç (hafif bir kavis olsun).\n4. Göğüs kaslarını kullanarak ellerini vücudunun önünde birleştir.\n5. Birleşme noktasında kaslarını 1 saniye sık ve yavaşça açıl.', 
'Dirseklerini hafif bükük (sabit) tut, sadece göğüs kaslarınla sıkıştır.'),

(5, 'CHEST', 'Chest Press Machine', 'Güvenli bir şekilde göğüs kaslarını yormak için idealdir.', 
'1. Makine koltuğunu, tutacaklar göğüs hizanıza gelecek şekilde ayarlayın.\n2. Sırtınızı ve başınızı arkalığa tam yaslayın.\n3. Tutacakları sıkıca kavrayın ve nefes vererek ileri doğru emin adımlarla itin.\n4. Kollarınızı tam kilitlemeden ağırlığı durdurun.\n5. Nefes alarak ağırlığı kontrollü bir şekilde başlangıç noktasına geri getirin.', 
'Sırtını arkalıktan ayırma, omuzlarını geride tut.'),
 
(6, 'CHEST', 'Push-Up (Şınav)', 'Kendi vücut ağırlığınla yapabileceğin en temel göğüs hareketidir.', 
'1. Ellerinizi yerleştirin (omuz genişliğinden biraz daha açık).\n2. Vücudunuzu ayak parmak uçlarınızdan başınıza kadar düz bir çizgi haline getirin.\n3. Nefes alarak göğsünüz yere yaklaşana kadar dirseklerinizi bükün.\n4. Göğsünüz yere değmek üzereyken nefes vererek kendinizi yukarı itin.\n5. Hareket boyunca karın kaslarınızı sıkı tutun.', 
'Kalçanı çok yukarı kaldırma veya aşağı sarkıtma, core kaslarını sık.'),

-- BACK
(7, 'BACK', 'Barbell Row', 'Sırt kalınlığı ve genel güç için en etkili hareketlerden biridir.', 
'1. Ayaklarını omuz genişliğinde aç ve barı omuz genişliğinde tut.\n2. Dizlerini hafif bük ve gövdeni yere paralel olana kadar öne eğ.\n3. Barı dizlerinin hizasından, karnının alt kısmına doğru çek.\n4. Çekerken kürek kemiklerini birbirine yaklaştırarak sıkıştır.\n5. Barı yavaşça aşağıya doğru bırakarak sırt kaslarını esnet.', 
'Belini düz tut, barı dizlerinin hemen altından çekmeye başla.'),

(8, 'BACK', 'Lat Pulldown', 'Sırt genişliğini (kanat) artıran temel bir harekettir.', 
'1. Makineye oturun ve dizlerinizi pedlerin altına sabitleyin.\n2. Barı omuz genişliğinden daha geniş bir açıyla kavrayın.\n3. Gövdenizi çok hafif geriye eğin.\n4. Barı üst göğüs hizanıza gelene kadar aşağı çekin ve sırtınızı sıkın.\n5. Ağırlığın sizi yukarı çekmesine izin verirken hareketi kontrollü yapın.', 
'Barı sırtına değil, ön göğsüne çek. Dirseklerini arkaya doğru yönlendir.'),

(9, 'BACK', 'Pull-Up (Barfiks)', 'Gövde üstü gücünü ve sırt genişliğini test eden zorlu bir hareket.', 
'1. Barı omuz genişliğinden geniş bir şekilde kavrayarak asılın.\n2. Kürek kemiklerini aşağı bastırarak hareketi başlatın.\n3. Kendinizi, çeneniz bar seviyesini geçene kadar yukarı çekin.\n4. Tepe noktada bir an durun ve kendinizi yavaşça aşağı bırakın.\n5. Kollarınızı tam açana kadar inmeyin, kontrollü kalın.', 
'Yarım hareket yapma, tam aşağı inip tam yukarı çek.'),

(10, 'BACK', 'Seated Cable Row', 'Orta sırt ve duruş kaslarını güçlendirir.', 
'1. Ayaklarınızı desteklere koyun ve dizlerinizi hafif bükük tutun.\n2. Tutacağı kavrayın ve gövdeniz dikleşene kadar geri oturun.\n3. Tutacağı göbeğinize doğru çekerken dirseklerinizi geriye itin.\n4. Sırtınızdaki kasların birbirine değdiğini hissedin.\n5. Kollarınızı yavaşça ileri uzatarak başlangıç pozisyonuna dönün.', 
'Gövdeni çok fazla ileri geri sallama, hareketi sırtınla yap.'),

(11, 'BACK', 'Single Arm Dumbbell Row', 'Her iki tarafın dengeli gelişmesini sağlayan bir izolasyon ve güç hareketidir.', 
'1. Bir elinizi ve aynı taraftaki dizinizi banka koyun.\n2. Diğer elinizle dumbbellı kavrayın.\n3. Dumbbellı kalçanıza doğru bir kavisle çekin.\n4. Çekiş sırasında omzunuzu kulağınızdan uzak tutun.\n5. Ağırlığı yavaşça aşağı bırakarak kanat kasınızı esnetin.', 
'Omzunu çok fazla aşağı düşürme, dirseğini vücuduna yakın tut.'),

(12, 'BACK', 'Face Pull', 'Arka omuz ve üst sırt sağlığı için kritik bir harekettir.', 
'1. Halatın yüksekliğini göz hizanıza ayarlayın.\n2. Halatı her iki elinizle kavrayın ve birkaç adım geri çekilin.\n3. Halatı yüzünüze doğru çekerken ellerinizi yanlara doğru açın.\n4. Birleşme noktasında arka omuzlarınızı ve üst sırtınızı iyice sıkın.\n5. Ağırlığı yavaşça geri bırakın.', 
'Hafif ağırlıkla yap, omuzlarını arkaya yaslayarak sıkıştır.'),

-- LEGS
(13, 'LEGS', 'Back Squat', 'Bacakların ve tüm vücudun temel güç kaynağıdır.', 
'1. Barı omuzlarınızın üzerine (trapes kaslarına) yerleştirin.\n2. Ayakları omuz genişliğinde açın ve parmak uçlarını hafif dışa çevirin.\n3. Kalçanızı geriye iterek sanki bir sandalyeye oturur gibi çömelin.\n4. Dizlerinizin ayak ucu yönünde kalmasına dikkat edin.\n5. Uyluk kemikleriniz yere paralel olduğunda, topuklarınızdan güç alarak kalkın.', 
'Topuklarını yerden kesme, dizlerinin ayak parmak ucunu çok geçmemesine bak.'),

(14, 'LEGS', 'Leg Press', 'Büyük ağırlıklarla bacaklara baskı uygulamak için tasarlanmıştır.', 
'1. Makineye oturun ve belinizi iyice arkalığa yaslayın.\n2. Ayaklarınızı platforma omuz genişliğinde yerleştirin.\n3. Güvenlik kollarını açın ve ağırlığı dizlerinizi hafif bükerek tutun.\n4. Platformu iterek bacaklarınızı uzatın (dizleri tam kilitlemeyin).\n5. Kontrollü bir şekilde ağırlığı aşağı indirin.', 
'Dizlerini tam kilitleme, hafif bükük kalsın.'),

(15, 'LEGS', 'Leg Extension', 'Ön bacak kaslarını (quadriceps) izole eder.', 
'1. Koltuğu diz kapağınız makinenin büküm noktasına gelecek şekilde ayarlayın.\n2. Ayaklarınızı pedin altına geçirin ve yanlardaki kollardan tutun.\n3. Bacaklarınızı yukarı doğru uzatın.\n4. Tepe noktada ön bacak kaslarınızı 1 saniye sıkın.\n5. Ağırlığı yavaşça aşağıya indirin ama ses çıkarmasına izin vermeyin.', 
'Ani hareketlerden kaçın, yavaşça indir.'),

(16, 'LEGS', 'Lying Leg Curl', 'Arka bacak (hamstring) kasları için en temel harekettir.', 
'1. Banka yüz üstü uzanın ve pedleri topuklarınızın hemen üzerine ayarlayın.\n2. Yanlardaki tutacakları kavrayın ve kalçanızı banka sabitleyin.\n3. Topuklarınızı kalçanıza doğru olabildiğince çekin.\n4. Arka bacaklarınızın yandığını hissedin.\n5. Ağırlığı yavaşça ve kontrolü kaybetmeden başlangıç noktasına bırakın.', 
'Kalçanı banktan kaldırmamaya çalış.'),

(17, 'LEGS', 'Romanian Deadlift', 'Kalça ve arka bacak esnekliği ve gücü için mükemmeldir.', 
'1. Barı kavrayın ve ayaktayken göğsünüzü dik tutun.\n2. Dizlerinizi çok hafif bükün (kilitli kalmasın).\n3. Gövdenizi kalçanızdan itibaren öne doğru eğin, kalçanızı geriye itin.\n4. Barı bacaklarınızın çok yakınından, kaval kemiklerine kadar indirin.\n5. Arka bacaklarınızda gerilme hissettiğinizde kalçalarınızı sıkarak doğrulun.', 
'Sırtın her zaman düz olmalı, kalçanı iyice geri it.'),

(18, 'LEGS', 'Lunges', 'Denge ve bacak koordinasyonunu geliştirir.', 
'1. Ayaktayken ellerinizi kalçanıza koyun veya dumbbell tutun.\n2. Bir bacağınızla ileriye büyük bir adım atın.\n3. Her iki diziniz de yaklaşık 90 derece bükülene kadar vücudunuzu indirin.\n4. Arka diziniz yere hafifçe yaklaşmalıdır.\n5. Ön ayağınızdan güç alarak başlangıç pozisyonuna geri dönün ve bacak değiştirin.', 
'Gövdeni dik tut, dizin yere sertçe çarpmasın.'),

-- SHOULDERS
(19, 'SHOULDERS', 'Overhead Press', 'Omuz kaslarının kütlesini artıran en temel pres hareketidir.', 
'1. Barı omuz hizasında kavrayın, dirsekleriniz hafifçe önde olsun.\n2. Ayaklarınızı yere sabitleyin ve karın kaslarınızı sıkın.\n3. Barı başınızın üzerinden yukarı doğru, kollarınız düzleşene kadar itin.\n4. Başınızı barın altından hafifçe öne çıkararak hareketi tamamlayın.\n5. Barı yavaşça omuz hizanıza geri indirin.', 
'Core bölgeni sıkı tut, belini çok fazla arkaya bükme.'),

(20, 'SHOULDERS', 'Dumbbell Lateral Raise', 'Omuzların geniş görünmesini sağlayan (yan omuz) hareketidir.', 
'1. İki elinize ağırlık alarak dik bir şekilde ayakta durun.\n2. Kollarınızı vücudunuzun yanlarında, dirseklerinizi çok hafif bükük tutun.\n3. Ağırlıkları yanlara doğru omuz hizanıza gelene kadar kaldırın.\n4. Sanki elinizdeki bir sürahiden su boşaltıyormuş gibi serçe parmağınızı hafif yukarı çevirin.\n5. Kontrollü bir şekilde indirin.', 
'Kollarını tam düz tutma, dirseklerini hafif bükük kalsın.'),

(21, 'SHOULDERS', 'Front Raise', 'Ön omuz kaslarını izole eder.', 
'1. Dik durun ve ağırlıkları uyluk kemiklerinizin önünde tutun.\n2. Bir kolunuzu (veya ikisini) göz hizanıza kadar öne doğru kaldırın.\n3. Hareket sırasında vücudunuzu sallamaktan kaçının.\n4. Omuz kasınızı tepe noktada hissedin.\n5. Ağırlığı yavaşça geri indirin.', 
'Vücudunu sallama, ağırlığı kontrollü kaldır.'),

(22, 'SHOULDERS', 'Arnold Press', 'Omuz kaslarını daha geniş bir açıdan çalıştırır.', 
'1. Sehpaya oturun ve ağırlıkları göğüs hizanızda, avuç içleri size bakacak şekilde tutun.\n2. Ağırlıkları yukarı iterken bileklerinizi 180 derece dışa doğru döndürün.\n3. Tepede avuçlarınız karşıya baksın.\n4. İnerken ağırlıkları tekrar döndürerek başlangıç pozisyonuna (avuçlar size bakar) dönün.', 
'Yavaş ve kontrollü dönüş yap omuz sağlığı için önemlidir.'),

-- BICEPS
(23, 'BICEPS', 'Barbell Curl', 'Pazıların boyutunu artıran en popüler harekettir.', 
'1. Barı omuz genişliğinde kavrayın ve dik durun.\n2. Dirseklerinizi vücudunuzun yanlarına sabitleyin.\n3. Barı sadece ön kollarınızı kullanarak omuzlarınıza doğru kıvırın.\n4. Tepe noktada pazılarınızı iyice sıkın.\n5. Barı yavaşça ve kası esneterek aşağı bırakın.', 
'Dirseklerini vücuduna yapışık tut, ileri geri hareket ettirme.'),

(24, 'BICEPS', 'Hammer Curl', 'Pazıların kalınlığını ve ön kolu geliştirir.', 
'1. Dumbbellları avuç içleriniz vücudunuza bakacak şekilde (çekiç tutuşu) kavrayın.\n2. Dirseklerini kımıldatmadan ağırlığı omuz hizanıza doğru kaldırın.\n3. Bu tutuş ön kollarınızı daha çok çalıştıracaktır.\n4. Kontrollü bir iniş yapın.\n5. Vücudunuzun sallanmamasına dikkat edin.', 
'Bileklerini sabit tut, bükülmesine izin verme.'),

(25, 'BICEPS', 'Preacher Curl', 'Hareketi izole ederek pazıların alt kısmını hedefler.', 
'1. Kolunuzu sehpaya tam temas edecek şekilde yerleştirin.\n2. Barı kavrayın ve vücudunuzun hareket etmesini engelleyin.\n3. Barı kendinize doğru çekerken sadece dirseğinizden bükülün.\n4. Pazılarınızın tamamen izole olduğunu göreceksiniz.\n5. Gerilimi kaybetmeden barı yavaşça aşağı uzatın.', 
'Bileğini çok fazla bükme, kolunu tam aşağı indirme (gerilimi kesme).'),

-- TRICEPS
(26, 'TRICEPS', 'Tricep Pushdown', 'Arka kolun şekillenmesini sağlar.', 
'1. Kablo makinesinin önünde durun ve halatı/barı kavrayın.\n2. Dirseklerinizi vücudunuzun yanlarına sabitleyin ve hafifçe öne eğilin.\n3. Kabloyu, kollarınız tamamen düzelene kadar aşağı doğru itin.\n4. Hareketin sonunda arka kollarınızı iyice sıkıştırın.\n5. Ağırlığı dirseklerinizi açmadan yavaşça yukarı bırakın.', 
'Sadece ön kolların hareket etsin, üst kolun sabit kalsın.'),

(27, 'TRICEPS', 'Skull Crusher', 'Arka kolun kütle kazanması için çok etkilidir.', 
'1. Banka sırt üstü uzanın ve ağırlığı (Z-Bar önerilir) kollarınız dik olacak şekilde tutun.\n2. Dirseklerinizi sabit tutarak barı kontrollüce alnınıza doğru indirin.\n3. Sadece ön kolunuz hareket etmelidir.\n4. Alnınızın hizasından ağırlığı geri yukarı itin.\n5. Dirseklerinizi birbirine yakın tutmaya çalışın.', 
'Dirseklerinin yanlara açılmasına izin verme, birbirine yakın tut.'),

(28, 'TRICEPS', 'Dips', 'Hem arka kolu hem de alt göğsü çalıştıran güçlü bir harekettir.', 
'1. Paralel barları kavrayın ve kendinizi yukarı iterek havada kalın.\n2. Dirseklerinizi bükerek vücudunuzu aşağı indirin.\n3. Omuzlarınız dirseklerinizin hizasına geldiğinde durun.\n4. Kendinizi kollarınız düzelene kadar yukarı geri itin.\n5. Arka kolunuzu hissederek hareketi tamamlayın.', 
'Gövdeni dik tutarsan arka kol, öne eğilirsen göğüs daha çok çalışır.'),

-- CORE
(29, 'CORE', 'Plank', 'Karın ve core bölgesinin dayanıklılığını artırır.', 
'1. Şınav pozisyonuna geçin ancak ağırlığınızı elleriniz yerine dirseklerinize verin.\n2. Vücudunuz başınızdan topuklarınıza kadar düz bir çizgi oluşturmalıdır.\n3. Karın kaslarınızı ve kalçanızı iyice sıkın.\n4. Bu pozisyonu titreyene kadar (veya belirlenen süre boyunca) koruyun.\n5. Nefes almayı unutmayın.', 
'Nefesini tutma, kalçanı düşürme.'),

(30, 'CORE', 'Hanging Leg Raise', 'Alt karın kasları için en etkili hareketlerden biridir.', 
'1. Kendinizi barfiks barından sarkıtın.\n2. Vücudunuzun sallanmasını durdurun.\n3. Karın kaslarınızı kullanarak bacaklarınızı (veya dizlerinizi) göğüs hizanıza kadar kaldırın.\n4. En üst noktada bir saniye bekleyin.\n5. Bacaklarınızı yavaşça ve sallanmadan aşağı indirin.', 
'Vücudunu sallama, bacaklarını kontrollü indir.'),

-- GLUTES
(31, 'GLUTES', 'Hip Thrust', 'Kalça kaslarını geliştirmek için bilimsel olarak en etkili harekettir.', 
'1. Sırtınızın üst kısmını bir banka yaslayın ve dizlerinizi büküp ayaklarınızı yere basın.\n2. Barı kalçanızın üzerine (pelvis bölgesi) yerleştirin.\n3. Kalçanızı havaya kaldırarak vücudunuzu dizlerinizden omzunuza kadar düz bir çizgi haline getirin.\n4. Tepe noktada kalçalarınızı 2 saniye boyunca sıkın.\n5. Kontrollü bir şekilde kalçanızı aşağı indirin.', 
'Tepe noktada kalçanı 1-2 saniye sık.'),

(32, 'GLUTES', 'Glute Kickback', 'Kalçayı şekillendiren izole bir harekettir.', 
'1. Kablo makinesinde ayak bileğinizi bağlayın veya emekleme pozisyonuna geçin.\n2. Bir bacağınızı geriye doğru kavisli bir şekilde tekme atar gibi uzatın.\n3. Kalçanızdaki gerilimi hissedin.\n4. Bacağınızı tam indirmeden tekrar tekmeyi atın.\n5. Karın kaslarınızı sıkın ki beliniz çok fazla bükülmesin.', 
'Belini aşırı çukurlaştırma, hareketi kalçanla yap.'),

-- YENI EKLENEN HAREKETLER (SCI-BASED 2024)

-- CHEST (Genişleme)
(33, 'CHEST', 'Incline Barbell Press', 'Üst göğüs kütlesi için en temel ve güçlü harekettir.', '1. Sehpaya 30-45 derece eğim verin.\n2. Barı omuz genişliğinden biraz daha geniş kavrayın.\n3. Barı kontrollüce üst göğsünüze indirin.\n4. Tepe noktada göğüs kaslarınızı sıkarak itin.', 'Barı köprücük kemiğine çok yakın indirme, hafif göğüs ortasına yönlendir.'),
(34, 'CHEST', 'High-to-Low Cable Fly', 'Alt göğüs liflerini ve göğüs ayrımını vurgular.', '1. Kabloları yukarıya sabitleyin.\n2. Kollarınızı genişçe açın ve öne doğru bir kavisle birleştirin.\n3. Ellerinizi kalça hizanızın önünde buluşturun.', 'Göğsünü öne çıkar, omuzlarını geride tut.'),
(35, 'CHEST', 'Chest Dips', 'Vücut ağırlığı ile alt göğüs ve kalori yakımı için harikadır.', '1. Dips barında kollarınız düz durun.\n2. Gövdenizi öne doğru eğin (göğüs odaklı).\n3. Dirseklerinizi dışa açarak inin ve itin.', 'Dik durursan arka kol, öne eğilirsen göğüs çalışır.'),

-- BACK (Genişleme)
(36, 'BACK', 'T-Bar Row', 'Sırt kalınlığı ve orta sırt detayları için efsanevi bir harekettir.', '1. Makineye yerleşin veya barın bir ucuna ağırlık takın.\n2. Gövdenizi 45 derece eğin.\n3. Ağırlığı karnınıza doğru çekip kürek kemiklerini sıkıştırın.', 'Bacaklarından güç alarak savurma, sadece sırtınla çek.'),
(37, 'BACK', 'Straight Arm Pulldown', 'Kanat kaslarını (Lat) izole ederek genişlik kazandırır.', '1. Kablo makinesinde barı kollarınız düz olacak şekilde tutun.\n2. Kollarınızı bükmeden barı uyluklarınıza kadar indirin.', 'Dirseklerini kitleme ama bükme de, tüm hareket omuz ekleminden olsun.'),
(38, 'BACK', 'Single Arm Lat Pulldown', 'Sırtın her iki tarafını eşit şekilde geliştirmek için idealdir.', '1. Kabloyu tek elle kavrayın.\n2. Dirseğinizi vücudunuza yapıştıracak şekilde aşağı çekin.', 'Gövdeni yana çok fazla yatırma.'),

-- LEGS (Genişleme)
(39, 'LEGS', 'Bulgarian Split Squat', 'Tek bacak gücü ve denge için en etkili (ve zorlu) harekettir.', '1. Bir ayağınızı arkadaki banka uzatın.\n2. Diğer bacağınızla öne doğru çökün.\n3. Gövdeniz hafif öne eğik olsun.', 'Öndeki ayağının topuğundan güç alarak yüksel.'),
(40, 'LEGS', 'Hack Squat', 'Dizlere daha az yük bindirerek ön bacakları (quads) maksimum yorar.', '1. Makineye sırtınızı yaslayın.\n2. Platformda ayaklarınızı omuz hizanıza yerleştirin.\n3. Derin bir şekilde çömelin ve kalkın.', 'Belini makineden ayırma.'),
(41, 'LEGS', 'Seated Calf Raise', 'Alt bacağın (Soleus) kalınlığını ve dayanıklılığını artırır.', '1. Makineye oturun ve pedleri dizinizin üzerine yerleştirin.\n2. Topuklarınızı olabildiğince aşağı indirin ve sonra parmak ucunda yükselin.', 'En alt noktada 1 saniye bekle (esneme için).'),

-- SHOULDERS (Genişleme)
(42, 'SHOULDERS', 'Seated Dumbbell Press', 'Omuzun genel boyutu ve gücü için en kontrollü tercihtir.', '1. Dik bir sehpaya oturun.\n2. Dumbbellları omuz hizanızdan yukarıya, kollar düzleşene kadar itin.', 'Dirseklerini tam yanlara değil, hafif öne (scapular plane) al.'),
(43, 'SHOULDERS', 'Pec Deck Rear Delt Fly', 'Arka omuz kaslarını en iyi izole eden makine hareketidir.', '1. Makineye yüzünüz pedlere bakacak şekilde oturun.\n2. Kollarınızı yanlara doğru, arka omuzlarınızı sıkarak açın.', 'Omuzlarını yukarı kaldırma (trapezleri devre dışı bırak).'),
(44, 'SHOULDERS', 'Cable Lateral Raise', 'Yan omuzda (deltoid) sürekli gerilim sağlayarak genişlik kazandırır.', '1. Kabloyu aşağıdan, vücudunuzun arkasından veya önünden kavrayın.\n2. Kolunuzu yan tarafa doğru omuz hizanıza kadar kaldırın.', 'Vücudunu sallamadan kontrollü kaldır.'),

-- BICEPS (Genişleme)
(45, 'BICEPS', 'Incline Dumbbell Curl', 'Pazıyı en uzun (esnemiş) pozisyonda çalıştırarak maksimum büyüme sağlar.', '1. 45 derece eğimli banka uzanın.\n2. Kollarınızı yere dik şekilde serbest bırakın ve yukarı kıvırın.', 'Dirseklerini öne kaçırmamaya çalış.'),
(46, 'BICEPS', 'Concentration Curl', 'Pazı tepesini (peak) belirginleştirmek için klasik bir izole harekettir.', '1. Banka oturun ve dirseğinizi bacağınızın içine sabitleyin.\n2. Dumbbellı yukarı doğru kontrollüce kıvırın.', 'Sadece ön kolun hareket etsin.'),

-- TRICEPS (Genişleme)
(47, 'TRICEPS', 'Overhead Cable Extension', 'Arka kolun uzun başını geliştirerek kolun arkadan dolu görünmesini sağlar.', '1. Kabloyu aşağıya sabitleyip halatı başınızın arkasına alın.\n2. Kollarınızı yukarı doğru, dirseklerinizi oynatmadan uzatın.', 'Üst kolun her zaman yere paralel veya hafif eğik kalsın.'),
(48, 'TRICEPS', 'Close Grip Bench Press', 'Hem arka kol kütlesi hem de triceps gücü için en ağır egzersizdir.', '1. Barı omuz genişliğinde veya biraz daha dar kavrayın.\n2. Barı göğüs hizanıza indirin ve tricepslerinizle güçlüce itin.', 'Ellerini çok dar tutma, bileklerine yük bindirme.'),

-- CORE (Genişleme)
(49, 'CORE', 'Cable Crunch', 'Karın kaslarına ağırlık direnci ekleyerek hacim kazandırır (six-pack).', '1. Kablo makinesinde diz çökün ve halatı başınızın yanlarına alın.\n2. Dirseklerinizi dizlerinize yaklaştıracak şekilde gövdenizi bükün.', 'Hareketi kalçanla değil, karın kaslarını bükerek yap.'),
(50, 'CORE', 'Ab Wheel Rollout', 'Core bölgesinin tüm stabilitesini ve gücünü test eden ileri seviye bir harekettir.', '1. Tekerleği dizlerinizin önünde tutun.\n2. Vücudunuz düzleşene kadar ileri yuvarlanın ve karın kaslarınızla geri çekilin.', 'Belini çukurlaştırma, karın kaslarını hep sıkı tut.'),

-- GLUTES (Genişleme)
(51, 'GLUTES', 'Romanian Deadlift (Dumbbell)', 'Arka bacak ve kalça (Glutes) için en iyi esneme/yükleme hareketlerinden biridir.', '1. Dik durun, dumbbellları bacaklarınızın yanında tutun.\n2. Kalçanızı geri iterek ağırlıkları diz altına kadar indirin.', 'Sırtın her zaman düz kalsın.')
;


-- YENI EKLENEN ILAVE HAREKETLER (TRENDING & DIY)
INSERT INTO exercises (id, muscle_group, name, description, instructions, tips) VALUES
(52, 'CHEST', 'Incline Cable Fly', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(53, 'CHEST', 'Low-to-High Cable Crossover', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(54, 'CHEST', 'Dumbbell Pullover', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(55, 'CHEST', 'Smith Machine Incline Press', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(56, 'CHEST', 'Pause Bench Press', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(57, 'CHEST', 'Wide Push-Up', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(58, 'CHEST', 'Close Grip Push-Up', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(59, 'CHEST', 'Single Arm Chest Press', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(60, 'CHEST', 'Incline Machine Press', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(61, 'CHEST', 'Guillotine Press', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(62, 'CHEST', 'Svend Press', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(63, 'CHEST', 'Incline Dumbbell Fly', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(64, 'CHEST', 'Incline Smith Press', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(65, 'CHEST', 'Incline Push-Up', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(66, 'CHEST', 'Decline Dumbbell Press', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(67, 'CHEST', 'Decline Cable Fly', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(68, 'CHEST', 'Decline Push-Up', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(69, 'CHEST', 'Pec Deck Fly', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(70, 'CHEST', 'Dumbbell Fly', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(71, 'CHEST', 'Machine Bench Press', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(72, 'CHEST', 'Push-Up Plus', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(73, 'CHEST', 'Deficit Push-Up', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(74, 'CHEST', 'Hex Press', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(75, 'CHEST', 'Cable Crossover', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(76, 'BACK', 'Wide Grip Pull-Up', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(77, 'BACK', 'Close Grip Lat Pulldown', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(78, 'BACK', 'Meadows Row', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(79, 'BACK', 'Reverse Grip Barbell Row', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(80, 'BACK', 'Rack Pull', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(81, 'BACK', 'Back Extension', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(82, 'BACK', 'Inverted Row', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(83, 'BACK', 'Pendlay Row', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(84, 'BACK', 'Machine High Row', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(85, 'BACK', 'Straight Arm Rope Pulldown', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(86, 'BACK', 'Seal Row', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(87, 'BACK', 'Neutral Grip Pull-Up', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(88, 'BACK', 'Underhand Pulldown', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(89, 'BACK', 'Wide Grip Lat Pulldown', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(90, 'BACK', 'Close Grip Cable Row', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(91, 'BACK', 'Chest Supported T-Bar Row', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(92, 'BACK', 'Dumbbell Row', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(93, 'BACK', 'Kroc Row', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(94, 'BACK', 'Yates Row', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(95, 'BACK', 'Hyperextension', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(96, 'BACK', 'Good Morning', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(97, 'BACK', 'Prone Cobra', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(98, 'BACK', 'Single Arm Cable Row', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(99, 'BACK', 'Helms Row', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(100, 'BACK', 'Chest-Supported Dumbbell Row', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(101, 'LEGS', 'Front Squat', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(102, 'LEGS', 'Sissy Squat', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(103, 'LEGS', 'Nordic Curl', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(104, 'LEGS', 'Standing Calf Raise', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(105, 'LEGS', 'Split Squat', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(106, 'LEGS', 'Goblet Squat', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(107, 'LEGS', 'Box Squat', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(108, 'LEGS', 'Jefferson Squat', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(109, 'LEGS', 'Step Down', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(110, 'LEGS', 'Cyclist Squat', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(111, 'LEGS', 'Pistol Squat', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(112, 'LEGS', 'Seated Leg Curl', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(113, 'LEGS', 'Single Leg Romanian Deadlift', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(114, 'LEGS', 'Glute Ham Raise', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(115, 'LEGS', 'Donkey Calf Raise', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(116, 'LEGS', 'Calf Press', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(117, 'LEGS', 'Walking Lunge', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(118, 'LEGS', 'Reverse Lunge', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(119, 'LEGS', 'Pendulum Squat', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(120, 'SHOULDERS', 'Machine Shoulder Press', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(121, 'SHOULDERS', 'Lean Away Lateral Raise', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(122, 'SHOULDERS', 'Rear Delt Cable Fly', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(123, 'SHOULDERS', 'Landmine Press', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(124, 'SHOULDERS', 'Y-Raise', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(125, 'SHOULDERS', 'Bradford Press', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(126, 'SHOULDERS', 'Cable Front Raise', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(127, 'SHOULDERS', 'Cable Upright Row', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(128, 'SHOULDERS', 'Plate Front Raise', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(129, 'SHOULDERS', 'Dumbbell Cuban Press', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(130, 'SHOULDERS', 'Machine Rear Delt Fly', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(131, 'SHOULDERS', 'Barbell Overhead Press', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(132, 'SHOULDERS', 'Dumbbell Shoulder Press', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(133, 'SHOULDERS', 'Front Plate Raise', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(134, 'SHOULDERS', 'Alternating Front Raise', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(135, 'SHOULDERS', 'Leaning Cable Lateral Raise', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(136, 'SHOULDERS', 'Rear Delt Row', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(137, 'SHOULDERS', 'Bent Over Rear Delt Raise', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(138, 'SHOULDERS', 'Cable Face Pull', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(139, 'SHOULDERS', 'Reverse Pec Deck', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(140, 'SHOULDERS', 'Egyptian Lateral Raise', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(141, 'SHOULDERS', 'Lu Raise', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(142, 'SHOULDERS', 'Upright Row', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(143, 'BICEPS', 'EZ Bar Curl', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(144, 'BICEPS', 'Spider Curl', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(145, 'BICEPS', 'Bayesian Cable Curl', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(146, 'BICEPS', 'Reverse Curl', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(147, 'BICEPS', 'Drag Curl', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(148, 'BICEPS', 'Cable Hammer Curl', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(149, 'BICEPS', '21s Curl', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(150, 'BICEPS', 'Machine Preacher Curl', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(151, 'BICEPS', 'High Cable Curl', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(152, 'BICEPS', 'Zottman Curl', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(153, 'BICEPS', 'Standing Dumbbell Curl', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(154, 'BICEPS', 'Cross Body Hammer Curl', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(155, 'BICEPS', 'Standing Barbell Curl', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(156, 'BICEPS', 'Alternating Dumbbell Curl', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(157, 'BICEPS', 'Cable Preacher Curl', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(158, 'BICEPS', 'One Arm Cable Curl', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(159, 'BICEPS', 'Incline Cable Curl', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(160, 'BICEPS', 'Scott Curl', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(161, 'BICEPS', 'Reverse EZ Curl', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(162, 'BICEPS', 'Pinwheel Curl', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(163, 'BICEPS', 'Bayesian Curl', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(164, 'BICEPS', 'Waiters Curl', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(165, 'TRICEPS', 'Rope Pushdown', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(166, 'TRICEPS', 'Reverse Grip Pushdown', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(167, 'TRICEPS', 'JM Press', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(168, 'TRICEPS', 'Overhead Dumbbell Extension', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(169, 'TRICEPS', 'Cable Kickback', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(170, 'TRICEPS', 'Dip Machine', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(171, 'TRICEPS', 'Diamond Push-Up', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(172, 'TRICEPS', 'Single Arm Rope Pushdown', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(173, 'TRICEPS', 'Bench Dip', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(174, 'TRICEPS', 'Lying Dumbbell Extension', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(175, 'TRICEPS', 'Cable Overhead Rope Extension', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(176, 'TRICEPS', 'Machine Triceps Extension', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(177, 'TRICEPS', 'Triceps Pushdown', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(178, 'TRICEPS', 'Straight Bar Pushdown', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(179, 'TRICEPS', 'V-Bar Pushdown', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(180, 'TRICEPS', 'Overhead Rope Extension', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(181, 'TRICEPS', 'Single Arm Overhead Extension', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(182, 'TRICEPS', 'Lying EZ Extension', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(183, 'TRICEPS', 'Tate Press', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(184, 'TRICEPS', 'Parallel Bar Dip', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(185, 'TRICEPS', 'Kickback', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(186, 'TRICEPS', 'Cross-Body Cable Extension', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(187, 'TRICEPS', 'Katana Extension', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(188, 'CORE', 'Side Plank', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(189, 'CORE', 'Pallof Press', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(190, 'CORE', 'Toe Touch Crunch', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(191, 'CORE', 'Bird Dog', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(192, 'CORE', 'Reverse Crunch', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(193, 'CORE', 'Cable Woodchopper', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(194, 'CORE', 'Hollow Body Hold', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(195, 'CORE', 'Sit-Up', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(196, 'CORE', 'Plank to Push-Up', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(197, 'CORE', 'V-Up', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(198, 'CORE', 'Crunch', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(199, 'CORE', 'Weighted Crunch', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(200, 'CORE', 'Machine Crunch', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(201, 'CORE', 'Decline Sit-Up', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(202, 'CORE', 'Knee Raise', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(203, 'CORE', 'Hanging Knee Raise', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(204, 'CORE', 'Flutter Kick', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(205, 'CORE', 'Bicycle Crunch', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(206, 'CORE', 'Side Bend', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(207, 'CORE', 'Russian Twist', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(208, 'CORE', 'Stir the Pot', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(209, 'CORE', 'Dragon Flag', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(210, 'CORE', 'L-Sit', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(211, 'CORE', 'Suitcase Carry', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(212, 'GLUTES', 'Barbell Glute Bridge', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(213, 'GLUTES', 'Banded Lateral Walk', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(214, 'GLUTES', 'Cable Hip Abduction', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(215, 'GLUTES', 'Single Leg Hip Thrust', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(216, 'GLUTES', 'Curtsy Lunge', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(217, 'GLUTES', 'Cable Pull Through', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(218, 'GLUTES', 'Kickstand Romanian Deadlift', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(219, 'GLUTES', 'Frog Bridge', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(220, 'GLUTES', 'Step-Up to Knee Drive', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(221, 'GLUTES', 'Deficit Reverse Lunge', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(222, 'GLUTES', 'Mini Band Clamshell', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(223, 'GLUTES', 'B-Stance Hip Thrust', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(224, 'GLUTES', 'Barbell Hip Thrust', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(225, 'GLUTES', 'Quadruped Kickback', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(226, 'GLUTES', 'Cable Abduction', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(227, 'GLUTES', 'Lateral Band Walk', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(228, 'GLUTES', 'Clamshell', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(229, 'GLUTES', 'Monster Walk', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(230, 'GLUTES', 'Sumo Deadlift', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(231, 'GLUTES', 'Deficit Split Squat', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(232, 'GLUTES', 'Goblet Sumo Squat', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(233, 'GLUTES', 'Reverse Hyperextension', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.'),
(234, 'GLUTES', 'Kas Glute Bridge', 'Bilimsel temelli ve etkili hipertrofi egzersizi.', '1. Hareketi kontrollü ve güvenli formda uygula.\n2. Kas gerilimine odaklanarak hedeflenen bölgeyi hisset.', 'Formu korumaya dikkat et ve ağırlıktan ziyade kas hissiyatına odaklan.');
